// Generated by CoffeeScript 1.8.0
(function() {
	$(function() {
		$("#loading").hide();
		return app.initialize();
	});

	window.app = {
		current: [],
		initialize: function() {
			this.setBind();
			
			return this.getJsonData();

		},
		setBind: function() {
			$('#submit').bind('click', (function(_this) {

				return function() {
					_this.search();
					return false;
				};
			})(this));
			return $('.link').bind('click', function() {
				app.search($(this).attr('data-menu'));
				return false;
			});
		},
		search: function(menu) {
			if (menu != null) {
				this.getSearchMenu(menu);
			}
			this.getSearchData();
			return this.setContents();
		},
		receive: function(value) {

			var spanHtml = "";

			if(value.delivery == true){
				spanHtml += '<span class="delivery">配送</span>';
			}

			if(value.airport == true){
				spanHtml += '<span class="airport">空港</span>';
			}

			if(value.shop == true){
				spanHtml += '<span class="shop">店頭</span>';
			}

			return spanHtml;
			
		},
		language: function(value) {

			var spanHtml = "";

			if(value.japanese == true){
				spanHtml += '<span class="japanese">日本語</span>';
			}

			if(value.english == true){
				spanHtml += '<span class="english">英語</span>';
			}

			if(value.kantai == true){
				spanHtml += '<span class="kantai">簡体字</span>';
			}

			if(value.hantai == true){
				spanHtml += '<span class="hantai">繁体字</span>';
			}

			return spanHtml;

		},
		setContents: function() {
			var html, top;

			var loading = $("#loading");
			var content = $("#table-sort");
			
			if (loading.is(":visible")) { return; }

			loading.show();
			content.hide();
			
			setTimeout(function() {
				loading.fadeOut();
				content.fadeIn();
			}, 1000);

			if (this.current.length === 0) {

				$("#contents_block #table-sort").html('<div class="not_found"><p>お探しの条件に一致する商品は見つかりませんでした。<br>条件を変更して検索してください。</p> </div>');

			} else {
				_.each(this.current, (function(_this) {

					return function(data) {
						return html +=
						'<tr>' +
							'<td class="footable-first-column"><span class="footable-toggle"></span>' + data.id + '位</td>'+ 
							'<td><img src="' + data.image_url + '" alt="' + data.name + '"></td>' +
							'<td data-value="' + data.receive.value + '">' + _this.receive(data.receive) + '</td>' + 
							'<td data-value="' + data.language.value + '">' + _this.language(data.language) + '</td>' + 
							'<td data-value="' + data.score.value + '">' + data.score.review + '</td>' + 
							'<td class="footable-last-column">' + 
								'<div class="btn_wrap">' +
									'<a href="'+ data.detail +'" class="btn02">もっと詳しく</a>' + 
									'<a href="'+ data.url +'" class="btn01" target="_blank">公式サイト</a>' + 
								'</div>' +
							'</td>' + 
						'</tr>';
					};

				})(this));
			}

			if($("#contents_block").hasClass('sorting')){

				/* Display table on sort.html page */

				$('#contents_block #table-sort tbody').html(html);

			}else{

				/* Display table on home page */
				
				$("#contents_block > ol, #left_column #title").remove();

				$("#contents_block").html('<div class="table-sort">' +
				'<table id="table-sort" data-sorting="true" class="footable toggle-circle">'+
					'<thead>' + 
						'<tr>' +
							'<th data-type="numeric" data-sort-ignore="true" data-direction="DESC">当サイト<br>人気ランキング</th>' +
							'<th data-sort-ignore="true">サイト名</th>' +
							'<th data-type="number">受取方法</th>' +
							'<th data-type="number">対応言語</th>' +
							'<th data-type="number">口コミ評価</th>' +
							'<th data-sort-ignore="true" data-hide="phone">&nbsp;</th>' +
						'</tr>' +
					'</thead>' +
					'<tbody></tbody>' +
				'</table>'+
				'</div>').addClass('top_ranking');

				if( html == "" || html == null){

					$("#contents_block").html('<div class="not_found"><p>お探しの条件に一致する商品は見つかりませんでした。<br>条件を変更して検索してください。</p> </div>').hide();

				}else{

					$('#contents_block #table-sort tbody').html(html);
					$('#contents_block').hide();

				}

				setTimeout(function() {
					$('#contents_block').fadeIn();
					$('#main_contents #select_form').fadeIn();
				}, 1000);

				$('#table-sort').footable().bind({

					'footable_sorted': function(e) {
						var loading = $("#loading");
						var content = $("#table-sort tbody");

						if (loading.is(":visible")) { return; }

						loading.show();
						content.hide();

						setTimeout(function() {
							loading.fadeOut();
							content.fadeIn();
						}, 1000);
					},
				});
			}

			$('#contents_block #table-sort th').removeClass('footable-sorted footable-sorted-desc');
			$('.ranking').text('ランキング一覧');
			top = Math.round($('#contents_block').offset().top);
			return window.scrollTo(0, top);
		},
		getSearchData: function() {
			var flags, posts;
			this.current = [];
			posts = {
				carrier: {
					ymobile: !_.isUndefined($("input[name='ymobile']:checked").val()),
					wimax: !_.isUndefined($("input[name='wimax']:checked").val()),
					au: !_.isUndefined($("input[name='au']:checked").val()),
					softbank: !_.isUndefined($("input[name='softbank']:checked").val())
				},
				period: {
					short: !_.isUndefined($("input[name='short']:checked").val()),
					long: !_.isUndefined($("input[name='long']:checked").val())
				},
				receive: {
					delivery: !_.isUndefined($("input[name='delivery']:checked").val()),
					airport: !_.isUndefined($("input[name='airport']:checked").val()),
					shop: !_.isUndefined($("input[name='shop']:checked").val())
				},
				language: {
					japanese: !_.isUndefined($("input[name='japanese']:checked").val()),
					english: !_.isUndefined($("input[name='english']:checked").val()),
					kantai: !_.isUndefined($("input[name='kantai']:checked").val()),
					hantai: !_.isUndefined($("input[name='hantai']:checked").val())
				},
				area: {
					hokkaido: !_.isUndefined($("input[name='hokkaido']:checked").val()),
					honshu: !_.isUndefined($("input[name='honshu']:checked").val()),
					shikoku: !_.isUndefined($("input[name='shikoku']:checked").val()),
					kyushu: !_.isUndefined($("input[name='kyushu']:checked").val()),
					okinawa: !_.isUndefined($("input[name='okinawa']:checked").val())
				}
			};
			flags = [];
			_.each(posts, (function(_this) {
				return function(value, key) {
					flags[key] = [];
					return _.each(value, function(value2, key2) {
						flags[key][key2] = [];
						if (value2) {
							return flags[key][key2].push(value2);
						} else {
							flags[key][key2].push(true);
							return flags[key][key2].push(false);
						}
					});
				};
			})(this));
			return this.current = _.filter(json.wifi, (function(_this) {
				return function(wifi) {
					return _.include(flags.carrier.ymobile, wifi.carrier.ymobile) && _.include(flags.carrier.wimax, wifi.carrier.wimax) && _.include(flags.carrier.au, wifi.carrier.au) && _.include(flags.carrier.softbank, wifi.carrier.softbank) && _.include(flags.period.short, wifi.period.short) && _.include(flags.period.long, wifi.period.long) && _.include(flags.receive.delivery, wifi.receive.delivery) && _.include(flags.receive.airport, wifi.receive.airport) && _.include(flags.receive.shop, wifi.receive.shop) && _.include(flags.language.japanese, wifi.language.japanese) && _.include(flags.language.english, wifi.language.english) && _.include(flags.language.kantai, wifi.language.kantai) && _.include(flags.language.hantai, wifi.language.hantai) && _.include(flags.area.hokkaido, wifi.area.hokkaido) && _.include(flags.area.honshu, wifi.area.honshu) && _.include(flags.area.shikoku, wifi.area.shikoku) && _.include(flags.area.kyushu, wifi.area.kyushu) && _.include(flags.area.okinawa, wifi.area.okinawa);
				};
			})(this));
		},
		getSearchMenu: function(menu, val) {
			$('input').prop('checked', false);
			return $("input[name='" + menu + "']").prop('checked', true);
		},
		getJsonData: function() {
			return $.getJSON("js/data.json?v=" + config.version, (function(_this) {
				return function(data) {
					return json.wifi = data.wifi;
				};
			})(this));
		}
	};

	window.json = {
		wifi: {}
	};

	window.config = {
		version: '0.01',
		is_debug: true,
		is_log: true
	};

	window.log = function(_log) {
		if (config.is_log) {
			return console.log(_log);
		}
	};

}).call(this);
